namespace ZeroBitGaming.Services {
    export class ItemService {

        static $inject = ['DiceSerivce', 'WordService']

        constructor(private DiceService: ZeroBitGaming.Services.DiceService, private WordService: ZeroBitGaming.Services.WordService) { }


        public regularItems() {
            var roll = this.DiceService.roll;
            var material = this.WordService.randomMaterial;
            var color = this.WordService.randomColor;
            var mod = this.WordService.randomWeaponModifiers;
            var lang = this.WordService.randomLanguage;
            var race = this.WordService.randomRace;
            switch (this.DiceService.roll(100)) {
                case 1: return `${roll(500)}ft of Rope`;
                case 2: return `${roll(3)} minor healing potion(s)`;
                case 3: return `${roll(3)} major healing potion(s)`;
                case 4: return `${roll(1000)} marbles`;
                case 5: return `Leather Coin Purse`;
                case 6: return `${roll(3)} vial(s) of poison`;
                case 7: return `${roll(10)} cask(s) of wine`;
                case 8: return `${roll(10)} match(es)`;
                case 9: return `A 10ft ${material()} pole`;
                case 10: return `${roll(5)} loaves of bread`;
                case 11: return `A pair of Iron Shackles`;
                case 12: return `A medical kit`;
                case 13: return `${roll(20)} lockpick(s)`;
                case 14: return `A ${roll(500)} ft long grappling hook`;
                case 15: return `A pen with ${roll(3) +1} wells of ink`;
                case 16: return `A mortar and pestle`;
                case 17: return `A lantern`;
                case 18: return `${roll(50)} oz of lantern oil`;
                case 19: return `A ${color()} backpack`;
                case 20: return `A ${color()} satchel`;
                case 21: return `A spyglass`;
                case 22: return `${roll(5)} pair(s) of ${color()} trousers`;
                case 23: return `A ${color()} hat`;
                case 24: return `A ${material()} harp`;
                case 25: return `A ${material()} lyre`;
                case 26: return `A jar of ${color()} dye`;
                case 27: return `A bucket of ${color()} paint`;
                case 28: return `A blacksmith's hammer`;
                case 29: return `${roll(1000)} peices of gold`;
                case 30: return `A ${color()} dress`;
                case 31: return `A ${color()} tunic`;
                case 32: return `A horn flask`;
                case 33: return `A ${material()} flute`;
                case 34: return `A ${color()} eyepatch`;
                case 35: return `A fiddle`;
                case 36: return `A walking stick`;
                case 37: return `${roll(4)} flasks of acid`;
                case 38: return `A ${color()} poncho`;
                case 39: return `A ${roll(30) + 10} ft long wooden ladder`;
                case 40: return `A small pot`;
                case 41: return `A vial of spider venom`;
                case 42: return `A ${race()} made fishing pole`;
                case 43: return `A large roll of hide`;
                case 44: return `A metal box full of kindling`;
                case 45: return `A small pouch of ${roll(20)} nails`;
                case 46: return `A flask of perfume`;
                case 47: return `A small case of makeup`;
                case 48: return `${roll(10) + 1} bottles of fresh water`;
                case 49: return `A bear trap`;
                case 50: return `A bottle of cooking oil`;
                case 51: return `A bag of holding`;
                case 52: return `A bag with ${roll(10) + 1}lbs of feathers`;
                case 53: return `A trunk of disguises`;
                case 54: return `A fireworks kit`;
                case 55: return `${roll(20) +1} sticks of dinamite`;
                case 56: return `A sign making kit`;
                case 57: return `A shovel`;
                case 58: return `A pipe and tabacco`;
                case 59: return `${roll(4) + 1} bars of soap`;
                case 60: return `${roll(200)}ft of ${color()} cloth`;
                case 61: return `A lasso`;
                case 62: return `A large net`;
                case 63: return `A sack of ${roll(30)} potatoes`;
                case 64: return `A portable stool`;
                case 65: return `A cast iron frying pan`;
                case 66: return `A bundle of ${roll(50)} sticks`;
                case 67: return `A guide to beast taming written in ${lang()}`;
                case 68: return `A falconry glove`;
                case 69: return `A monocle`;
                case 70: return `A tattoo kit`;
                case 71: return `An invitation to a royal event`;
                case 72: return `A sail for a boat`;
                case 73: return `A keg of black powder`;
                case 74: return `${roll(30)}ft tall retractable stilts`;
                case 75: return `A keg of ale`;
                case 76: return `A sled`;
                case 77: return `A hairdresser's kit`;
                case 78: return `A letter opener`;
                case 79: return `A jar of wax`;
                case 80: return `A hairbrush`;
                case 81: return `A hand mirror`;
                case 82: return `A jug of moonshine`;
                case 83: return `A masterwork ring`;
                case 84: return `A skeleton key to an unknown building`;
                case 85: return `A writing kit`;
                case 86: return `An empty diary`;
                case 87: return `${roll(5) + 1}lbs of clay`;
                case 88: return `A teaching certificate`;
                case 89: return `A glass prisim`;
                case 90: return `A parasol`;
                case 91: return `A tanning kit`;
                case 92: return `A taxidermy kit`;
                case 93: return `A guide to ventriloquism`;
                case 94: return `A cloak`;
                case 95: return `A tea set`;
                case 96: return `A ${material()} gong`;
                case 97: return `${roll(10)} burlap sacks`;
                case 98: return `${roll(10)} used rags`;
                case 99: return `${material()} dentures`;
                case 100: return `A jar of candy`;
            }
        }

        public mysteriousTrinkets() {
            var roll = this.DiceService.roll;
            var material = this.WordService.randomMaterial;
            var color = this.WordService.randomColor;
            var mod = this.WordService.randomWeaponModifiers;
            var lang = this.WordService.randomLanguage;
            var race = this.WordService.randomRace;
            switch (this.DiceService.roll(100)) {
                case 1: return `${roll(5) + 1} pages from an old diary`;
                case 2: return `A ${color()} scroll detailing an ancient magic of some sort`;
                case 3: return `A musty ${color()} potion in a ${material()} bottle`;
                case 4: return `An old ${material()} bottle`;
                case 5: return `A glass eyeball`;
                case 6: return `The claw of a small animal`;
                case 7: return `A(n) ${mod()} ${material()} greatsword that was brought to you by a dying courier`;
                case 8: return `A book detailing the various trees of the world with many notes scribbled in the margins`;
                case 9: return `${roll(10)} ${material()} sphere(s) in a ${mod()} ${material()} box`;
                case 10: return `${roll(20) + 1} ${color()} eggs`;
                case 11: return `A plush doll of an unknown diety`;
                case 12: return `A working VooDoo doll (just add hair & blood!)`;
                case 13: return `A ${material()} mask that is always wet`;
                case 14: return `${roll(100)} sheets of blank paper`;
                case 15: return `A ${mod()} puppet`;
                case 16: return `A cookbook written in ${lang()}`;
                case 17: return `A ${lang()} to ${lang()} Dictionary`;
                case 18: return `A pouch of ${race()} hair`;
                case 19: return `A pouch of dried fruit`;
                case 20: return `The skull of a ${race()}`;
                case 21: return `A locked Adamantine case that you found buried under a tree in the forest`;
                case 22: return `A painting of a ${race()} with an inscription written in ${lang()}`;
                case 23: return `A portable ${material()} chess set`;
                case 24: return `${roll(40)} ${mod()} stamps with a picture of a ${race()} on them`;
                case 25: return `A spool of ${color()} thread`;
                case 26: return `A pouch of sharpened ${race()} teeth`;
                case 27: return `Old love letters written in ${lang()}`;
                case 28: return `A pair of ${color()} underwear`;
                case 29: return `A plush doll of a ${race()}`;
                case 30: return `A ${mod()} ${material()} statue of a ${race()}`;
                case 31: return `A map of an unknown area`;
                case 32: return `A set of full plate armor made of magically enchanted ${material()}`;
                case 33: return `A strap of leather with the numbers ${roll(50)} ${roll(50)} and ${roll(50)} branded into it`;
                case 34: return `A clock with no hands but you always seem to know what time it is when you look at it`;
                case 35: return `The hilt to an ancient sword`;
                case 36: return `A poem written in ${lang()}`;
                case 37: return `A small bottle of ${color()} powder`;
                case 38: return `A pair of ${mod()} pants`;
                case 39: return `A special septre that used to belong to an important ${race()} king`;
                case 40: return `A jar of mint leaves`;
                case 41: return `A book entitled "speaking to your food" with half the pages missing`;
                case 42: return `A flag of an unknown nation`;
                case 43: return `A bottle of never ending fresh air`;
                case 44: return `Orders from the king`;
                case 45: return `A ${material()} spoon`;
                case 46: return `A small wooden box`;
                case 47: return `A deck of Tarot cards missing the death card`;
                case 48: return `A broken, blood splattered, carriage wheel`;
                case 49: return `An empty sheath with ornate carvings that seem to tell the tale of a fallen hero`;
                case 50: return `A cracked crystal ball that sometimes seems to be whispering to you`;
                case 51: return `An enchanted, talking book that has lost its memory`;
                case 52: return `An anatomically correct, heart shaped rock`;
                case 53: return `A pair of goggles`;
                case 54: return `A short yellow wand with a pink tip and an inscription reading "No. 2"`;
                case 55: return `A chipped ${color()} dragon's tooth`;
                case 56: return `A seal that says "sancutary" written in every language`;
                case 57: return `A potion of pure anger`;
                case 58: return `A vase full of sand dollars`;
                case 59: return `A noose`;
                case 60: return `A jar of old garlic`;
                case 61: return `Moose Armor`;
                case 62: return `An angel's feather`;
                case 63: return `An arrow too long for any bow`;
                case 64: return `A bottle full of demon fire`;
                case 65: return `A picture of something so funny everyone laughs when they see it`;
                case 66: return `A box of letters from someone who signs his name as death`;
                case 67: return `A claw foot bathtub`;
                case 68: return `The diary of an ancient being`;
                case 69: return `A complete encyclopedia of everything`;
                case 70: return `A magic shell that answers yes or no questions`;
                case 71: return `A wooden stick that is never quite the same size`;
                case 72: return `A ring haunted dead bards`;
                case 73: return `Magic Belt of holding up pants`;
                case 74: return `A potion of facial hair growth`;
                case 75: return `Complex instructions for making a mysterious poition`;
                case 76: return `Guide to being terribly mysterious 2nd edition`;
                case 77: return `An old top hat; there seems to be some magic in it`;
                case 78: return `16 candles`;
                case 79: return `The most comfortable boots in the world`;
                case 80: return `Unlucky horseshoes that you can't get rid of unless someone willingly takes them after knowing their secret`;
                case 81: return `A book that contains a list of orders and if anyone reads them you must carry them out`;
                case 82: return `The bust of a ${race()} without a nose`;
                case 83: return `A gargoyle egg`;
                case 84: return `${12000} counterfeit copper coins`;
                case 85: return `the deed to a mansion that you haven't been able to find`;
                case 86: return `Earmuffs that completely block all sound`;
                case 87: return `The key to someone's heart`;
                case 88: return `A kaleidoscope`;
                case 89: return `A rainstick`;
                case 90: return `An engagement ring`;
                case 91: return `${mod()} ${material()} sandals`;
                case 92: return `A potion of voice amplification`;
                case 93: return `A mask that allows you to breathe in any situation as long as you are wearing it`;
                case 94: return `A small of jar of seasoning that makes anything taste like the best food ever.`;
                case 95: return `A headband of intimidation`;
                case 96: return `A peice of paper that reads anything written on it out loud in any language. Every 3 minutes.`;
                case 97: return `A mysterious box that has a new message inside it everyday`;
                case 98: return `A really ugly shirt`;
                case 99: return `Soap that makes you appear dirtier the cleaner you get`;
                case 100: return `Pipe of sober-mindedness: the more you smoke the less high you get`;
            }
        }
        }
    }
